name: Windows RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup RDP
      run: |
        net user runneradmin Password@123 /add
        net localgroup administrators runneradmin /add
        net user runneradmin /active:yes

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        echo "USERNAME: runneradmin"
        echo "PASSWORD: Password@123"
